services:
  flask-app:
    build: .
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          cpus: "3"  # Utilize more CPU resources
          memory: 3G  # Increase memory allocation
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"  # Bind the container port to the host port
    command: gunicorn -w 4 -t 120 -k uvicorn.workers.UvicornWorker --threads 4 --worker-connections 1000 channel_id_route:app --bind 0.0.0.0:8000
