services:
  flask-app:
    build: .
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0  # Correct Redis URL configuration
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 3G
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker all_routes:app --bind 0.0.0.0:8000 --timeout 600

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - flask-app

  celery-beat:
    build: .
    command: celery -A app.celery beat --loglevel=info
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - flask-app
