version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    deploy:
      replicas: 3  # Number of container instances
      resources:
        limits:
          cpus: "2"  # Limit CPU usage to 2 CPUs
          memory: 2G  # Limit memory usage to 2GB
      restart_policy:
        condition: on-failure
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker channel_id_route:app --bind 0.0.0.0:8000