services:
  flask-app:
    build: .
    environment:
      - FLASK_ENV=production
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker channel_id_route:app --bind 0.0.0.0:8000